# Generated by Django 6.0.5 on 2026-05-25 13:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=50)),
                ('type', models.CharField(default='info', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(default='LIVERSEG_AI_AE', max_length=50)),
                ('port', models.IntegerField(default=104)),
                ('ip_address', models.CharField(default='192.168.10.45', max_length=50)),
                ('auto_route', models.BooleanField(default=True)),
                ('validate_on_receive', models.BooleanField(default=True)),
                ('compression', models.CharField(default='Lossless JPEG-LS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('modality', models.CharField(max_length=100)),
                ('status', models.CharField(default='Ready', max_length=20)),
                ('has_lesions', models.BooleanField(default=False)),
                ('lesion_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('metrics', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('radiologist', 'Radiologist'), ('admin', 'Hospital Admin'), ('researcher', 'AI Researcher'), ('clinician', 'Clinician'), ('technician', 'Imaging Technician')], default='radiologist', max_length=20)),
                ('department', models.CharField(default='Radiology', max_length=100)),
                ('hospital', models.CharField(default='St. Luke Medical Center', max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('scans_reviewed', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_index', models.IntegerField()),
                ('liver_size', models.FloatField(default=0)),
                ('liver_x', models.FloatField(default=0)),
                ('liver_y', models.FloatField(default=0)),
                ('lesion_size', models.FloatField(default=0)),
                ('lesion_x', models.FloatField(default=0)),
                ('lesion_y', models.FloatField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='api.patient')),
            ],
        ),
    ]
