# Generated by Django 6.0.5 on 2026-05-26 11:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('radiologist', 'Radiologist'), ('admin', 'Hospital Admin'), ('researcher', 'AI Researcher'), ('clinician', 'Clinician'), ('technician', 'Imaging Technician')], default='radiologist', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('scans_reviewed', models.IntegerField(default=0)),
                ('activities', models.JSONField(default=list)),
                ('pacs_config', models.JSONField(default=api.models.default_pacs_config)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('modality', models.CharField(max_length=100)),
                ('status', models.CharField(default='Ready', max_length=20)),
                ('has_file', models.BooleanField(default=False)),
                ('has_lesions', models.BooleanField(default=False)),
                ('lesion_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('slices', models.JSONField(default=list)),
            ],
        ),
    ]
