# Generated by Django 6.0.5 on 2026-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ct_scan',
            field=models.FileField(blank=True, help_text='Raw CT volume: NIfTI (.nii/.nii.gz) or DICOM (.dcm)', null=True, upload_to='ct_scans/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_mask',
            field=models.FileField(blank=True, help_text='AI-generated liver segmentation mask image', null=True, upload_to='liver_masks/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='CT slice preview thumbnail for UI display', null=True, upload_to='preview_images/'),
        ),
    ]
