# Generated by Django 6.0.5 on 2026-05-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_department_remove_user_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
