# Generated by Django 6.0.5 on 2026-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slices',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Slice',
        ),
    ]
