# Generated by Django 6.0.5 on 2026-05-26 10:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_slices_delete_slice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='PacsConfig',
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='pacs_config',
            field=models.JSONField(default=api.models.default_pacs_config),
        ),
    ]
