version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-liverseg_db}
      - POSTGRES_USER=${DB_USER:-liverseg_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-Vijay30390}
    ports:
      - "5433:5432" # Exposed on 5433 to avoid conflicts if local pg is running

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-liverseg_db}
      - DB_USER=${DB_USER:-liverseg_user}
      - DB_PASSWORD=${DB_PASSWORD:-Vijay30390}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,backend}
      - CORS_ALLOWED_ORIGINS=http://localhost
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A core worker -l info
    volumes:
      - media_volume:/app/media
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-liverseg_db}
      - DB_USER=${DB_USER:-liverseg_user}
      - DB_PASSWORD=${DB_PASSWORD:-Vijay30390}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume:
  static_volume:
